### ISSUE TITLE
Remove nested styling inside the `.tbxforms` class

### ISSUE THREAD

**Issue by helenb** [torchbox/tbxforms#40]
https://github.com/torchbox/tbxforms/blob/main/tbxforms/static/sass/tbxforms.scss nests all the BEM classes created for the various form elements inside a `.tbxforms` class. This means that if you want to override the `tbxforms` styles, you have to write more nested code in the override.

```
.tbxforms   .tbxforms-error-message {
...
}
```

Is it possible to just remove the nesting in `tbxforms.scss`?

**Comment by kbayliss** [comment]
Given that all classes are prepended with `.tbxforms-...` (e.g. `.tbxforms-clearfix` instead of just `.clearfix`), the parent `.tbxforms` class can probably be removed.

I vaguely recall adding this to limit the scope only to affect tbxforms components and not interfere with the GOV.UK Design System that is installed separately, though I cannot say for sure.

A PR would be welcome :)!

**Comment by helenb** [comment]
MR now created: https://github.com/torchbox/tbxforms/pull/49
